### ISSUE TITLE
nipples.js

### ISSUE THREAD

**Issue by pandosme** [bartbutenaers/node-red-contrib-ui-joystick#1]
My dashboard was empty (no graphics).  My investigation shows that my browser could not load nipples.js (code 404).  There are no other error logs. Maybe there is something in my server/nodered setup that prevents this.

**Comment by bartbutenaers** [comment]
Hi Pandos,

The loading of the libraries has already caused me a lot of headaches in the past, with other nodes of me.  There are lots of different configurations, causing this kind of troubles...

+ Can you please share a screenshot of the error in the browser log.
+ And can you share which kind of settings you have configured (related to urls) in your settings.js file.  For example this setting:
   ```
   //ui: { path: "ui" },
   ```
Bart

**Comment by pandosme** [comment]
I suspected that my path configurations may be the cause.

 

httpAdminRoot: '/admin',

httpRoot: '/',

httpStatic: '/data/static/',

ui: { path: "" }

 

Reverting to default Node-RED settings resolved the problem.  There are cases when I want my dashboard ui to be the root (/) entry point.  If you ever get time for a solution…  For now I am fine as I want to play around with controlling PTZ in my camera.  I will start with your example using your ONVIF-node.

 

/Fred

 

Från: bartbutenaers <notifications@github.com> 
Skickat: den 11 januari 2021 11:03
Till: bartbutenaers/node-red-contrib-ui-joystick <node-red-contrib-ui-joystick@noreply.github.com>
Kopia: Pandos Me <fred@juhlin.me>; Author <author@noreply.github.com>
Ämne: Re: [bartbutenaers/node-red-contrib-ui-joystick] nipples.js (#1)

 

Hi Pandos,

The loading of the libraries has already caused me a lot of headaches in the past, with other nodes of me. There are lots of different configurations, causing this kind of troubles...

*	Can you please share a screenshot of the error in the browser log.
*	And can you share which kind of settings you have configured (related to urls) in your settings.js file. For example this setting: 

*         //ui: { path: "ui" },

Bart

**Comment by bartbutenaers** [comment]
Hi Fred,
I had a similar [issue](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/86#issuecomment-753406485) last week.  Does it work when you use `ui: { path: "/" }` instead of `ui: { path: "" }`?

**Comment by pandosme** [comment]
Setting ui path to "/" resolved the issue.
