### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by Balro76** [bartbutenaers/node-red-contrib-ui-joystick#2]
Hello

I love this, so I wanted to setup the joystick to control a car, but I ran into a problem

The images show that the JSON should output position, but it does not output that

I am trying to calculate how far the knob is pushed so I can control speed and steering

Is this a bug ?  Right now I am using this to calculate the position but its not very good
x = radius *  Math.cos(angle)
y = radius *  Math.sin(angle)

thanks and awesome timing on the creation, I only just decided to do this for my students in code club

**Comment by bartbutenaers** [comment]
Hi @Balro76,

yes the position was removed from the first version.  Unfortunately I'm recovering from an operation, so I won't be able to develop for a couple of months.  You can "try" to add the position yourself in your .node-red/node-red-contrib-ui-joystick/joystick.js file:
```
$scope.send({
   payload: {
      ...,  This are the existing output msg fields (with comma at the end!)
      position: {
         x: data.position.x,
         y: data.position.y
      }
   },
   topic: evt
});
```
But I cannot test this, or support you with it!!!!!!!!!!!!
If it works fine please give feedback and I will finalize/publish it on npm in a couple of months.
Bart

**Comment by Balro76** [comment]
Thanks Bart, so happy you replied

For now I am just restricting it to up down, and left right controls and that is a great work around. But will have a go at altering the code as you suggested so we can add more features later

I would love to give you a copy of the node red export, I have a full working RC car now that you can control from an iPad thanks to your joysticks

I might post it when its all finished later

Hope you get well soon, and again thanks for the reply and the awesome Node Red Joystick!
