### ISSUE TITLE
Not working after deploy of flow

### ISSUE THREAD

**Issue by fromCologne** [bartbutenaers/node-red-contrib-ui-joystick#3]
Nice node but,
when I redeploy my NR flow there is a scaling or positioning problem.
After a NR restart I can click with my mouse cursor on the inner circle and move the inner circle with short mouse moves. Works great.

But after a redeploy of the flow, if I click on the inner circle it moves at once to the outer right end. To control the inner circle I have to move the (clicked) mouse cursor wide to the left of the screen. There I can find a new ´virtual´ middle of the joystick.

My joystick node is currently in a dashboard tab on right half of the dashboard window. I tried to arrange the tab to the left side of the window and the behavior is similar, but the virtual middle is quite nearer to the joystick.
It seems the middle of the joystick follows the main window of the NR dashboard and is not scaled to the tab.

**Comment by bartbutenaers** [comment]
Hi @fromCologne,

Can you share a simple test flow that I can use to reproduce the problem?
I tried a couple of things, but I cannot reproduce something like that...
Thanks !!
Bart

**Comment by fromCologne** [comment]
Hi Bart,
nice to hear your. Hope you are well.

> simple test flow

I tried the test flow from you and only add a second dashboard tab to it. The tab with joystick is on the right side.
After import works well, but after some small change and a redeploy problem like I described above.

I use NR version 1.3.5 (Docker-Image) and node-red-dashboard 2.30.0.

`[{"id":"4e8a0545.bc0cf4","type":"debug","z":"6824f08f.58786","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":370,"y":120,"wires":[]},{"id":"662dfc83.76ec34","type":"change","z":"6824f08f.58786","name":"Right","rules":[{"t":"set","p":"pan_speed","pt":"msg","to":"0.5","tot":"num"},{"t":"set","p":"action","pt":"msg","to":"continuousMove","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":660,"y":340,"wires":[["3a3a2b59.a6db54"]]},{"id":"b28baf2c.f99ae8","type":"change","z":"6824f08f.58786","name":"Left","rules":[{"t":"set","p":"pan_speed","pt":"msg","to":"-0.5","tot":"num"},{"t":"set","p":"action","pt":"msg","to":"continuousMove","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":660,"y":300,"wires":[["3a3a2b59.a6db54"]]},{"id":"8e982669.2d5108","type":"change","z":"6824f08f.58786","name":"Up","rules":[{"t":"set","p":"tilt_speed","pt":"msg","to":"0.5","tot":"num"},{"t":"set","p":"action","pt":"msg","to":"continuousMove","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":660,"y":220,"wires":[["3a3a2b59.a6db54"]]},{"id":"3281fec.5492182","type":"change","z":"6824f08f.58786","name":"Down","rules":[{"t":"set","p":"tilt_speed","pt":"msg","to":"-0.5","tot":"num"},{"t":"set","p":"action","pt":"msg","to":"continuousMove","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":660,"y":260,"wires":[["3a3a2b59.a6db54"]]},{"id":"3a3a2b59.a6db54","type":"onvif-ptz","z":"6824f08f.58786","name":"","deviceConfig":"64cddf80.2469a8","profileName":"","action":"","panSpeed":0,"tiltSpeed":0,"zoomSpeed":0,"panPosition":0,"tiltPosition":0,"zoomPosition":0,"panTranslation":0,"tiltTranslation":0,"zoomTranslation":0,"time":1,"preset":"","presetName":"","stopPanTilt":true,"stopZoom":true,"configurationToken":"","x":848,"y":220,"wires":[[]]},{"id":"303b964e.ecdfc2","type":"switch","z":"6824f08f.58786","name":"payload.direction.angle","property":"payload.direction.angle","propertyType":"msg","rules":[{"t":"eq","v":"up","vt":"str"},{"t":"eq","v":"down","vt":"str"},{"t":"eq","v":"left","vt":"str"},{"t":"eq","v":"right","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":400,"y":240,"wires":[["8e982669.2d5108"],["3281fec.5492182"],["b28baf2c.f99ae8"],["662dfc83.76ec34"]],"outputLabels":["up","down","left","right"]},{"id":"aa202f83.5555f8","type":"ui_joystick","z":"6824f08f.58786","name":"","group":"a434ad35.e8a6b","order":1,"width":5,"height":5,"trigger":"all","timeInterval":"1000","useThemeColor":true,"color":"#000000","threshold":"0.5","directions":"all","shape":"circle","centerAtRelease":true,"x":200,"y":160,"wires":[["303b964e.ecdfc2","4e8a0545.bc0cf4"]]},{"id":"4203fa68.850c4c","type":"ui_text","z":"6824f08f.58786","group":"86fae76f.7ac0a","order":0,"width":"15","height":"4","name":"","label":"Sample Text","format":"{{msg.payload}}","layout":"row-spread","x":230,"y":380,"wires":[]},{"id":"64cddf80.2469a8","type":"onvif-config","xaddress":"192.168.1.27","port":"8080","name":"webcam1"},{"id":"a434ad35.e8a6b","type":"ui_group","name":"Joystick demo","tab":"77a8be2.16f914","order":2,"disp":true,"width":5,"collapse":false},{"id":"86fae76f.7ac0a","type":"ui_group","name":"Group 2","tab":"77a8be2.16f914","order":1,"disp":true,"width":15},{"id":"77a8be2.16f914","type":"ui_tab","name":"Joystick","icon":"dashboard","disabled":false,"hidden":false}]`

![Testflow_crop](https://user-images.githubusercontent.com/7251335/125232858-cf63b500-e2dd-11eb-8a37-d77e9a684be5.jpg)


See you
Ingo

**Comment by bartbutenaers** [comment]
Hey Ingo,
I have imported your flow and tried all kind of things, but it keeps working fine...
Are there any errors in the browser console log, or anything else that can allow me to troubleshoot this?
I have no idea what could cause this in your case...

**Comment by fromCologne** [comment]
Hi Bart,
nothing in the (Firefox) log.
But I think I found the reason. It´s only a problem with Firefox not with Edge. Both actual patched versions.
If you redeploy the NR flow you have to close/reopen the tab in Firefox browser too. No problem with Edge. Chrome not tested.
Many thanks for your hint.
See you
Ingo

**Comment by bartbutenaers** [comment]
Ok, thanks for the analysis and the feedback!
