### ISSUE TITLE
Limited moves

### ISSUE THREAD

**Issue by ebolisa** [bartbutenaers/node-red-contrib-ui-joystick#4]
Hi,
I cannot get it to work properly. When I click on it, the center circle jumps to the extreme right (on a pi and extreme upper right on win) and I can only move it few millimeters up and down. I've made no changes to the node so, I'm using it as is. What am I doing wrong?
TIA

**Comment by bartbutenaers** [comment]
Hello @ebolisa,
Well that is hard to tell.
+ Are there errors in your browser console log (via your browser developer tools)?
+ Does the problem also occur when you put the joystick at another position in your dashboard layout?  Some users reported problems at certain positions...

Bart

**Comment by ebolisa** [comment]
Thanks Bart. It worked in a different part of the dashboard.

**Comment by bartbutenaers** [comment]
@ebolisa,
Thanks for sharing your feedback!
Yes indeed, it does not work well in some locations of the dashboard.  Don't know why.  And can't solve it, because the library (which I am using) isn't maintained anymore unfortunately...
So therefore I am going to close this issue.
Kind regards
